added prometheus

diff --git a/.github/workflows/ci-pipeline.yml b/.github/workflows/ci-pipeline.yml
--- a/.github/workflows/ci-pipeline.yml
+++ b/.github/workflows/ci-pipeline.yml
@@ -2,9 +2,6 @@ name: CI Pipeline for Spring Boot JAR (AuthService)
 
 on:
   push:
-    branches:
-      - branch1
-      - main
 
 jobs:
   build-and-deploy:
@@ -41,16 +38,30 @@ jobs:
       - name: Check Docker status
         run: docker info
 
-      # 5. Build and test with Maven + Testcontainers
-      - name: Build and test with Maven (Testcontainers)
+      # 5. Maven downloads common-events from GitHub Packages to Actions
+      - name: Set up Maven settings.xml for GitHub Packages
+        run: |
+          mkdir -p ~/.m2
+          echo '<settings>
+            <servers>
+              <server>
+                <id>github-filter</id>
+                <username>${GITHUB_ACTOR}</username>
+                <password>${{ secrets.GITHUB_TOKEN }}</password>
+              </server>
+            </servers>
+          </settings>' > ~/.m2/settings.xml
+
+      # 6. Build and test with Maven + Testcontainers
+      - name: Build and test
         env:
           TESTCONTAINERS_RYUK_DISABLED: "true"      # Disable Ryuk for better stability
           MAVEN_OPTS: "-Dmaven.repo.local=.m2"      # Use local Maven cache
         run: |
           mvn -B clean install -e -X -Dspring.test.constructor.autowire.mode=all
-          pkill -f surefirebooter || true           # Kill any stuck test processes
+        #pkill -f surefirebooter || true           # Kill any stuck test processes
 
-      # 6. Upload test reports if tests fail
+      # 7. Upload test reports if tests fail
       - name: Upload Surefire Reports
         if: failure()
         uses: actions/upload-artifact@v4
@@ -58,13 +69,13 @@ jobs:
           name: surefire-reports
           path: target/surefire-reports/
 
-      # 7. Prepare JAR for SonarCloud analysis
+      # 8. Prepare JAR for SonarCloud analysis
       - name: Prepare for Sonar analysis
         run: |
           mkdir -p target/unpacked-libs
           unzip -q -j target/*.jar 'BOOT-INF/lib/*.jar' -d target/unpacked-libs || echo "No libraries found in JAR"
 
-      # 8. Static code analysis with SonarCloud
+      # 9. Static code analysis with SonarCloud
       - name: SonarCloud Scan
         uses: SonarSource/sonarcloud-github-action@v2
         env:
@@ -78,21 +89,21 @@ jobs:
             -Dsonar.java.binaries=target/classes
             -Dsonar.java.libraries=target/unpacked-libs/*.jar
 
-      # 9. Create keys for Docker build
+      # 10. Create keys for Docker build
       - name: Create keys
         run: |
           mkdir -p src/main/resources/keys
           echo "${{ secrets.PRIVATE_KEY }}" > src/main/resources/keys/private.pem
           echo "${{ secrets.PUBLIC_KEY }}" > src/main/resources/keys/public.pem
 
-      # 10. Log in to Docker Hub
+      # 11. Log in to Docker Hub
       - name: Login to Docker Hub
         uses: docker/login-action@v2
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.TOKEN_FOR_AUTHSERVICE }}
 
-      # 11. Build and push Docker image (using local Docker socket)
+      # 12. Build and push Docker image (using local Docker socket)
       - name: Build and Push Docker Image
         if: success()
         run: |
